# Uncomment this line to define a global platform for your project

# pods生成framework而不是默认的静态库
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'CPFWaterfallFlowLayoutApp' do

    platform :ios, '9.0'

    # 链式调用
    pod 'CPFChain'
end

post_install do |pi|
   pi.pods_project.targets.each do |t|
       t.build_configurations.each do |bc|
           if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
             bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
           end
       end
   end
end
